package viewtests;

import static cs3500.animator.util.AnimationReader.parseFile;
import static org.junit.Assert.assertTrue;

import cs3500.animator.model.animationmodel.AnimationModel;
import cs3500.animator.model.animationmodel.AnimationModelImpl;
import cs3500.animator.view.IView;
import cs3500.animator.view.SVGView;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import org.junit.Test;


/**
 * Class with tests for an SVGView of an Animation.
 */
public class TestSVGView {

  IView view;

  @Test
  public void testSVG() throws IOException {
    String in = "buildings.txt";
    Readable fRead = new FileReader(in);
    Writer writer = new FileWriter(new File("abc.txt"));
    AnimationModel model = parseFile(fRead, new AnimationModelImpl.Builder());

    this.view = new SVGView(model, writer, 50);

    this.view.play();
    writer.close();
    assertTrue(("<svg width=\"800\" height=\"800\" version=\"1.1\"\n"
        + "     xmlns=\"http://www.w3.org/2000/svg\">\n"
        + "<rect id=\"background\" x=\"0\" y=\"0\" width=\"800\" height=\"800\" fill=\""
        + "rgb(33,94,248)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" /><animate attr"
        + "ibuteType=\"XML\" attributeName=\"fill\" from=\"rgb(33,94,248)\" to=\"rgb(16,45,248)\" "
        + "begin = \"1000ms\" dur = \"800ms\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(33,94,248)\" to="
        + "\"rgb(16,45,248)\" begin = \"1000ms\" dur = \"800ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"B0\" x=\"80\" y=\"424\" width=\"100\" height=\"326\" fill=\"rgb("
        + "0,0,0)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"B1\" x=\"260\" y=\"365\" width=\"100\" height=\"385\" fill=\"rgb"
        + "(0,0,0)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"B2\" x=\"440\" y=\"375\" width=\"100\" height=\"375\" fill=\"rgb("
        + "0,0,0)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"B3\" x=\"620\" y=\"445\" width=\"100\" height=\"305\" fill=\"rgb"
        + "(0,0,0)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window000\" x=\"100\" y=\"850\" width=\"20\" height=\"20\" fill="
        + "\"rgb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate a"
        + "ttributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"850\" "
        + "to=\"710\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window001\" x=\"140\" y=\"850\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"850\" to=\"7"
        + "10\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window010\" x=\"100\" y=\"890\" width=\"20\" height=\"20\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate at"
        + "tributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"890\" "
        + ""
        + "to=\"670\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window011\" x=\"140\" y=\"890\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"890\" to=\"6"
        + "70\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window020\" x=\"100\" y=\"930\" width=\"20\" height=\"20\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"930\" to=\""
        + "630\""
        + " fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window021\" x=\"140\" y=\"930\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate a"
        + "ttributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"930\" to="
        + "\"630\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"r"
        + "gb(255,255,0)\" begin = \"1640ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window030\" x=\"100\" y=\"970\" width=\"20\" height=\"20\" fill=\"rgb(255,25"
        + "5,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"970\" to=\"590"
        + "\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window031\" x=\"140\" y=\"970\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribut"
        + "eType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"970\" to=\"590\""
        + " fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window040\" x=\"100\" y=\"1010\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate att"
        + "ributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1010\" t"
        + "o=\"550\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window041\" x=\"140\" y=\"1010\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1010\" to=\"5"
        + "50\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\""
        + "rgb(255,255,0)\" begin = \"2940ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window050\" x=\"100\" y=\"1050\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1050\" to=\""
        + "510\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window051\" x=\"140\" y=\"1050\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1050\" to=\""
        + "510\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window060\" x=\"100\" y=\"1090\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1090\" to=\""
        + "470\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\""
        + ""
        + "rgb(255,255,0)\" begin = \"2940ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window061\" x=\"140\" y=\"1090\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1090\" to=\"4"
        + "70\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"rg"
        + "b(255,255,0)\" begin = \"1860ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window100\" x=\"280\" y=\"-750\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-750\" t"
        + "o=\"710\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window101\" x=\"320\" y=\"-750\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate att"
        + "ributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-750\""
        + " to=\"710\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" t"
        + "o=\"rgb(255,255,0)\" begin = \"2160ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window110\" x=\"280\" y=\"-710\" width=\"20\" height=\"20\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate "
        + "attributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-"
        + "710\" to=\"670\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\""
        + " to=\"rgb(255,255,0)\" begin = \"1900ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window111\" x=\"320\" y=\"-710\" width=\"20\" height=\"20\" fill=\"r"
        + "gb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate "
        + "attributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\""
        + "-710\" to=\"670\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window120\" x=\"280\" y=\"-670\" width=\"20\" height=\"20\" fill=\""
        + "rgb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate "
        + "attributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-6"
        + "70\" to=\"630\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window121\" x=\"320\" y=\"-670\" width=\"20\" height=\"20\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribute"
        + "Type=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-670\" to=\"630\" "
        + "fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window130\" x=\"280\" y=\"-630\" width=\"20\" height=\"20\" fill=\"rgb(255,25"
        + "5,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribute"
        + "Type=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-630\" to=\"590\" "
        + "fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window131\" x=\"320\" y=\"-630\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + ""
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-630\" to=\"590"
        + "\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"rgb"
        + "(255,255,0)\" begin = \"2960ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window140\" x=\"280\" y=\"-590\" width=\"20\" height=\"20\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribut"
        + "eType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-590\" to=\"550\""
        + " fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window141\" x=\"320\" y=\"-590\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-590\" to=\"5"
        + "50\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window150\" x=\"280\" y=\"-550\" width=\"20\" height=\"20\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-550\" to=\""
        + "510\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window151\" x=\"320\" y=\"-550\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-550\" to"
        + "=\"510\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" t"
        + "o=\"rgb(255,255,0)\" begin = \"1980ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window160\" x=\"280\" y=\"-510\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate at"
        + "tributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-510\""
        + " to=\"470\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window161\" x=\"320\" y=\"-510\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-510\" to"
        + "=\"470\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window170\" x=\"280\" y=\"-470\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-470\" to="
        + "\"430\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window171\" x=\"320\" y=\"-470\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-470\" to=\"43"
        + "0\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window180\" x=\"280\" y=\"-430\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + ""
        + ""

        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-430\" to=\"390"
        + "\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window181\" x=\"320\" y=\"-430\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribut"
        + "eType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-430\" to=\""
        + "390\" "
        + "fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window200\" x=\"460\" y=\"850\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"850\" to=\"71"
        + "0\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"r"
        + "gb(255,255,0)\" begin = \"2540ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window201\" x=\"500\" y=\"850\" width=\"20\" height=\"20\" fill=\"rgb(255,2"
        + ""
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"850\" to=\"710"
        + "\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window210\" x=\"460\" y=\"890\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"890\" to=\"67"
        + "0\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\""
        + "rgb(255,255,0)\" begin = \"1660ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window211\" x=\"500\" y=\"890\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate at"
        + "tribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"890\" to=\""
        + "670\""
        + " fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window220\" x=\"460\" y=\"930\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"930\" to=\""
        + "630\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window221\" x=\"500\" y=\"930\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"930\" to=\"630\""
        + "fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window230\" x=\"460\" y=\"970\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"

        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"970\" to="
        + "\"590\" "
        + "fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window231\" x=\"500\" y=\"970\" width=\"20\" height=\"20\" fill=\"rgb(255,255"
        + ",255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribut"
        + "eType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"970\" to=\"590\" "
        + "fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window240\" x=\"460\" y=\"1010\" width=\"20\" height=\"20\" fill=\"rgb(255,25"
        + "5,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteT"
        + "ype=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1010\" to=\"550\" "
        + "fill=\"freeze\" />\n"
        + "\n"

        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window241\" x=\"500\" y=\"1010\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
            + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1010\" " +
            "to=\"550\""
        + " fill=\"freeze\" />\n"
        + "\n"

        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"r"
        + "gb(255,255,0)\" begin = \"2240ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window250\" x=\"460\" y=\"1050\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1050\" to=\""
        + "510\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\""
        + "rgb(255,255,0)\" begin = \"2560ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window251\" x=\"500\" y=\"1050\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1050\" to=\"5"
        + "10\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window260\" x=\"460\" y=\"1090\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1090\" to=\"47"
        + "0\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window261\" x=\"500\" y=\"1090\" width=\"20\" height=\"20\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1090\" to=\"470"
        + "\" fill=\"freeze\" />\n"
        + "\n"

        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"rg"
        + "b(255,255,0)\" begin = \"1920ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window270\" x=\"460\" y=\"1130\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1130\" to=\"43"
        + "0"
        + "\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window271\" x=\"500\" y=\"1130\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attri"
        + "buteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"1130\" to=\"4"
        + "30\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"

        + "<rect id=\"window300\" x=\"640\" y=\"-750\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribute"
        + "Type=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-750\" to=\"710\" "
        + "f"
        + "ill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window301\" x=\"680\" y=\"-750\" width=\"20\" height=\"20\" fill=\"rgb(255"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attribu"
        + "teType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-750\" to=\"71"
        + "0\""
        + ""
        + " fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to=\"rg"
        + "b(255,255,0)\" begin = \"2700ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window310\" x=\"640\" y=\"-710\" width=\"20\" height=\"20\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-710\" to="
        + "\"670\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to"
        + "=\"rgb(255,255,0)\" begin = \"2060ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window311\" x=\"680\" y=\"-710\" width=\"20\" height=\"20\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate att"
        + "ributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-710\" to"
        + "=\"670\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window320\" x=\"640\" y=\"-670\" width=\"20\" height=\"20\" fill=\"rg"
        + "b(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate a"
        + "ttributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-670\""
        + " to=\"630\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window321\" x=\"680\" y=\"-670\" width=\"20\" height=\"20\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attr"
        + "ibuteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-670\" "
        + "to=\"630\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window330\" x=\"640\" y=\"-630\" width=\"20\" height=\"20\" fill=\"r"
        + "gb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate att"
        + "ributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-630\" "
        + "to=\"590\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" "
        + "to=\"rgb(255,255,0)\" begin = \"1620ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window331\" x=\"680\" y=\"-630\" width=\"20\" height=\"20\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate att"
        + "ributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-630\" "
        + "to=\"590\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to"
        + "=\"rgb(255,255,0)\" begin = \"2380ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window340\" x=\"640\" y=\"-590\" width=\"20\" height=\"20\" fill=\"rg"
        + "b(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate a"
        + "ttributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-59"
        + "0\" to=\"550\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window341\" x=\"680\" y=\"-590\" width=\"20\" height=\"20\" fill=\""
        + "rgb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate "
        + "attributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-590\""
        + " to=\"550\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window350\" x=\"640\" y=\"-550\" width=\"20\" height=\"20\" fill=\""
        + "rgb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate "
        + "attributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\""
        + "-550\" to=\"510\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window351\" x=\"680\" y=\"-550\" width=\"20\" height=\"20\" fill=\"r"
        + "gb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate a"
        + "ttributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-5"
        + "50\" to=\"510\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" "
        + "to=\"rgb(255,255,0)\" begin = \"2000ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<rect id=\"window360\" x=\"640\" y=\"-510\" width=\"20\" height=\"20\" fill=\"rg"
        + "b(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate attrib"
        + "uteType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-510\" to=\"47"
        + "0\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to"
        + "=\"rgb(255,255,0)\" begin = \"1980ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"

        + "<rect id=\"window361\" x=\"680\" y=\"-510\" width=\"20\" height=\"20\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />    <animate att"
        + "ributeType=\"xml\" begin=\"400ms\" dur=\"800ms\" attributeName=\"y\" from=\"-510\" "
        + "to=\"470\" fill=\"freeze\" />\n"
        + "\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(255,255,255)\" to"
        + "=\"rgb(255,255,0)\" begin = \"1980ms\" dur = \"100ms\" fill=\"freeze\"/>\n"
        + "\n"
        + "</rect>\n"
        + "\n"
        + "<ellipse id=\"moon\" cx=\"250\" cy=\"250\" rx=\"50\" ry=\"50\" fill=\"rgb(229,229"
        + ",255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" />\n"

        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"eclipse\" cx=\"450\" cy=\"50\" rx=\"50\" ry=\"50\" fill=\"rgb(33,"
        + "94,248)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"20ms\" /><animate attrib"
        + "uteType=\"XML\" attributeName=\"fill\" from=\"rgb(33,94,248)\" to=\"rgb(16,45,248)\""
        + " begin = \"1000ms\" dur = \"800ms\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"XML\" attributeName=\"fill\" from=\"rgb(33,94,248)\" to=\""
        + "rgb(16,45,248)\" begin = \"1000ms\" dur = \"800ms\" fill=\"freeze\"/>\n"
        + "    <animate attributeType=\"xml\" begin=\"1000ms\" dur=\"800ms\" attributeName=\"cx\" "
        + "from=\"450\" to=\"280\" fill=\"freeze\" />\n"
        + "\n"
        + "    <animate attributeType=\"xml\" begin=\"1000ms\" dur=\"800ms\" attributeName=\"c"
        + "y\" from=\"50\" to=\"230\" fill=\"freeze\" />\n"
        + "\n"
        + "\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star0\" cx=\"226\" cy=\"69\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\" "
        + "visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2160ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star1\" cx=\"588\" cy=\"214\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\""
        + " visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2400ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star2\" cx=\"492\" cy=\"80\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\" "
        + "visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2200ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star3\" cx=\"377\" cy=\"289\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\" "
        + "visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1860ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star4\" cx=\"711\" cy=\"284\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\" "
        + "visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1660ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star5\" cx=\"511\" cy=\"263\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\" "
        + "visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1940ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star6\" cx=\"532\" cy=\"73\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\""
        + " visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1840ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star7\" cx=\"335\" cy=\"68\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,255)\""
        + " visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2340ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star8\" cx=\"314\" cy=\"150\" rx=\"3\" ry=\"3\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1720ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star9\" cx=\"173\" cy=\"284\" rx=\"3\" ry=\"3\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1760ms\" />\n"

        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star10\" cx=\"722\" cy=\"105\" rx=\"3\" ry=\"3\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1800ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star11\" cx=\"527\" cy=\"267\" rx=\"3\" ry=\"3\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2580ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star12\" cx=\"771\" cy=\"197\" rx=\"3\" ry=\"3\" fill=\"r"
        + "gb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1720ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star13\" cx=\"769\" cy=\"182\" rx=\"3\" ry=\"3\" fill=\"r"
        + "gb(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2260ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star14\" cx=\"513\" cy=\"81\" rx=\"3\" ry=\"3\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1960ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star15\" cx=\"624\" cy=\"152\" rx=\"3\" ry=\"3\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2280ms\" />\n"

        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star16\" cx=\"494\" cy=\"255\" rx=\"3\" ry=\"3\" fill=\"rgb"
        + "(255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2120ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star17\" cx=\"408\" cy=\"66\" rx=\"3\" ry=\"3\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1780ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star18\" cx=\"553\" cy=\"270\" rx=\"3\" ry=\"3\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2260ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star19\" cx=\"111\" cy=\"200\" rx=\"3\" ry=\"3\" fill=\"rgb(2"
        + "55,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1880ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star20\" cx=\"740\" cy=\"81\" rx=\"3\" ry=\"3\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2060ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star21\" cx=\"798\" cy=\"140\" rx=\"3\" ry=\"3\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2520ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star22\" cx=\"187\" cy=\"128\" rx=\"3\" ry=\"3\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1780ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star23\" cx=\"137\" cy=\"233\" rx=\"3\" ry=\"3\" fill=\"rgb("
        + "255,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1920ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star24\" cx=\"247\" cy=\"156\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255"
        + ",255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2400ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star25\" cx=\"262\" cy=\"122\" rx=\"3\" ry=\"3\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2240ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star26\" cx=\"325\" cy=\"272\" rx=\"3\" ry=\"3\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2120ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star27\" cx=\"415\" cy=\"185\" rx=\"3\" ry=\"3\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2340ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star28\" cx=\"677\" cy=\"140\" rx=\"3\" ry=\"3\" fill=\"rgb(255,2"
        + "55,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2380ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star29\" cx=\"49\" cy=\"249\" rx=\"3\" ry=\"3\" fill=\"rgb(255,25"
        + "5,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1920ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star30\" cx=\"391\" cy=\"318\" rx=\"3\" ry=\"3\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2460ms\" />\n"
        + "</ellipse>\n"
        + "\n"

        + "<ellipse id=\"star31\" cx=\"188\" cy=\"239\" rx=\"3\" ry=\"3\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2420ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star32\" cx=\"553\" cy=\"235\" rx=\"3\" ry=\"3\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2180ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star33\" cx=\"659\" cy=\"104\" rx=\"3\" ry=\"3\" fill=\"rgb(25"
        + "5,255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1880ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star34\" cx=\"286\" cy=\"114\" rx=\"3\" ry=\"3\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1680ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star35\" cx=\"652\" cy=\"329\" rx=\"3\" ry=\"3\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1840ms\" />\n"

        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star36\" cx=\"694\" cy=\"270\" rx=\"3\" ry=\"3\" fill=\"rgb(255,25"
        + "5,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2300ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star37\" cx=\"116\" cy=\"279\" rx=\"3\" ry=\"3\" fill=\"rgb(255,255,"
        + "255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1980ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star38\" cx=\"607\" cy=\"305\" rx=\"3\" ry=\"3\" fill=\"rgb(255"
        + ",255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"1980ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "<ellipse id=\"star39\" cx=\"465\" cy=\"165\" rx=\"3\" ry=\"3\" fill=\"rgb(255,"
        + "255,255)\" visibility=\"hidden\" >\n"
        + "<set attributeName=\"visibility\" to=\"visible\" begin=\"2540ms\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "\n"
        + "</svg>").equals(this.view.toString()));

  }
}
